### ISSUE TITLE
Englische Übersetzung

### ISSUE THREAD

**Issue by KerstinKleinTHK** [gbv/ubo_koeln#11]
https://github.com/gbv/ubo_koeln/blob/572f9ddcbfe92213678f4715232f459143229157/src/main/resources/config/ubo_koeln/messages_en.properties#L70

Bitte einfügen: <strong>Please note that the entries for the years 2020, 2021 and 2022 are currently being processed with priority.</strong> Entries from other vintages will not be lost; they will be released at a later date.

**Comment by kkrebs** [comment]
fixed in 84f81abb6406357bf84658cfec2f1f5086a00daf
